name = "NonlinearOptimizationTestFunctions"
uuid = "3180b13f-e8d1-40aa-806b-3e6ce7522c6b"
authors = ["aox"]
version = "0.6.5"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Documenter = "1.14.1"
ForwardDiff = "0.10"
HTTP = "1.10.19"
JSON3 = "1.14.3"
LinearAlgebra = "1"
NLopt = "1.2.1"
Optim = "1.13.2"
Optimization = "5.0.0"
OptimizationNLopt = "0.3.6"
OptimizationOptimJL = "0.4.6"
Revise = "3.12.3"
Test = "1.11.0"
Zygote = "0.7.10"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
docs = ["Documenter"]
examples = ["NLopt"]
test = ["Test", "Zygote"]
