name = "NonlinearOptimizationTestFunctions"
uuid = "3180b13f-e8d1-40aa-806b-3e6ce7522c6b"
authors = ["aox"]
version = "0.3.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"  

[compat]
Documenter = "1.14.1"
ForwardDiff = "0.10"
LinearAlgebra = "1"
Optim = "1.13.2"
Test = "1.11.0"
Zygote = "0.7.10"
julia = "1"


[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
docs = ["Documenter"]
examples = ["NLopt"]
test = ["Test", "Zygote"]


