# C:\Users\uweal\NonlinearOptimizationTestFunctions.jl\docs\Project.toml

name = "NonlinearOptimizationTestFunctions"
# Die UUID des Hauptpakets
uuid = "3180b13f-e8d1-40aa-806b-3e6ce7522c6b" 
authors = ["Uwe Alex"]
version = "0.6.8"

[deps]
# Das Hauptpaket selbst (als lokale Abhängigkeit)
NonlinearOptimizationTestFunctions = "3180b13f-e8d1-40aa-806b-3e6ce7522c6b"

# Nur die Pakete, die im docs/make.jl direkt benötigt werden
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
# Fügen Sie hier nur hinzu, was in docs/make.jl importiert wird!